scrape_configs:
  - job_name: 'URL Shortener'
    metrics_path: '/api/v1/actuator/prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: ['host.docker.internal:1009']
        labels:
          application: 'URL Shortener service'

